### ISSUE TITLE
The extension cannot be started on WSL2

### ISSUE THREAD

**Issue by ghost** [JonasRock/XML_GridView#2]
For the VSCode running on Windows 11 host and opening the project located on the WSL2, the extension does not start. Here is the log:
```
2024-07-25 11:22:34.279 [info] ExtensionService#_doActivateExtension jonasrock.xml-grid-view, startup: false, activationEvent: 'onCommand:xml-grid-view.restartGridView'
2024-07-25 11:22:34.296 [error] Activating extension jonasrock.xml-grid-view failed due to an error:
2024-07-25 11:22:34.296 [error] Error: Cannot find module './communicationHandler'
Require stack:
- /home/name/.vscode-server/extensions/jonasrock.xml-grid-view-0.2.0/out/extension.js
- /home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/loader.js
- /home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/bootstrap-amd.js
- /home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.S._load (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:179:6035)
    at Function.n._load (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:176:31788)
    at Function.i._load (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:141:34301)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/name/.vscode-server/extensions/jonasrock.xml-grid-view-0.2.0/out/extension.js:9:32)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.S._load (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:179:6035)
    at Function.n._load (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:176:31788)
    at Function.i._load (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:141:34301)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Function.i [as __$__nodeRequire] (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/loader.js:5:98)
    at m.xb (/home/name/.vscode-server/bin/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/workbench/api/node/extensionHostProcess.js:176:32967)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
```
@JonasRock  Can you suggest any next steps to fix this?

P.S. VSCode info:
```Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
```
XML Grid View:
```
Name: XML Grid View
Id: jonasrock.xml-grid-view
Description: Alternative visual representation for xml files
Version: 0.2.0
Publisher: Jonas Rock
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=JonasRock.xml-grid-view
Published
2021-03-05, 02:41:16
Last released
2021-03-05, 02:43:34
Last updated
2024-06-19, 17:43:04
Identifier
jonasrock.xml-grid-view
```

**Comment by ghost** [comment]
P.P.S. WSL system: `Ubuntu 20.04.6 LTS`
